#14 fixture operational saas database
exasol/saas-api-python pull request #27
Opened 2024-04-30 14:23 UTC by ckunki

Closes #14

2024-05-01 07:44 UTC, ahsimb commented on test/integration/api_access.py
> +    def get_database(self, database_id: str):
Consider annotating the return type: `openapi.models.database.Database`

2024-05-01 07:44 UTC, ahsimb commented on test/integration/api_access.py
> +        def poll_status():
I would just wait for the Status.RUNNING for a limited period of time. What if they decide to be more verbose and introduce another transitional status? Your code will start breaking every time it hits this new status. Yes, in theory, you can save some time by terminating earlier if you see an unexpected status. However, it may rarely happen in practice. If either of the service URL, account id, or PAT is invalid you will get an exception (or an error HTTP code). Otherwise, in 99% of cases, the DB should be started successfully. If the success rate is smaller then that we have a major problem with SaaS.

2024-05-06 08:14 UTC, ckunki commented on test/integration/api_access.py
> +    def get_database(self, database_id: str):
fixed in next push.

2024-05-06 08:17 UTC, ckunki commented on test/integration/api_access.py
> +        def poll_status():
Fixed in last push.

2024-05-06 17:02 UTC, tomuben commented on test/integration/api_access.py
> +                    LOG.info(f"Ignoring status code {response.status_code}.")
```suggestion
                    LOG.warning(f"Ignoring status code {response.status_code}.")
```

2024-05-06 17:12 UTC, tomuben commented on test/integration/api_access.py
> +        if poll_status() not in success:
Does it make sense to try to connect to the database here, via pyexasol?
I mean, maybe for the tests the fixture is written for, there is no need to connect to the db; but if the test need to connect to the db, it would be good to fail already here in the fixture....

2024-05-07 06:18 UTC, ckunki commented on test/integration/api_access.py
> +                    LOG.info(f"Ignoring status code {response.status_code}.")
Thanks - fixed in next push

2024-05-07 06:22 UTC, ckunki commented on test/integration/api_access.py
> +        if poll_status() not in success:
Actually, I think this is a good proposal.
I will discuss with @tkilias.
On the other hand, this will require an additional dependency to pyexasol. 
But maybe this is acceptable or will come in anyway at some point in time. 
And last not least: I personally need some additional hint about how to obtain the db credentials. :thinking:

2024-05-07 06:45 UTC, tkilias requested changes

2024-05-07 06:45 UTC, tkilias commented on test/integration/api_access.py
> +MINIMUM_IDLE_TIME = timedelta(minutes=15)
We maybe should define this as constant in the package itself, this might be useful also for users of the package

2024-05-07 06:45 UTC, tkilias commented on test/integration/api_access.py
> +MINIMUM_LIFETIME = timedelta(seconds=30)
Same as with MINIMUM L_IDLE_TIME

2024-05-07 06:45 UTC, tkilias commented on test/integration/api_access.py
> +                idle_time=int(MINIMUM_IDLE_TIME.seconds / 60),
Can't timedelta directly return minutes?

2024-05-07 06:45 UTC, tkilias commented on test/integration/api_access.py
> +    return f"{username}-{timestamp}"
This still can break for long user names, we need to shorten it differently. Furthermore, we still should mention from where the DB is from. So, mu suggestion would be something like the following 

{Timestamp}_{project_short_tag}_{username} and this overall string truncated to length

@tomuben what is the max length for the DB name in SaaS

2024-05-07 06:45 UTC, tkilias commented on test/integration/api_access.py
> +                name=db_name,
Below I see we use us-east, we should think about which region we use.

2024-05-07 06:51 UTC, tkilias commented on test/integration/api_access.py
> +                response = self.delete_database(db.id, ignore_delete_failure)
here might be retries a good idea

2024-05-07 07:19 UTC, tkilias requested changes

2024-05-07 07:19 UTC, tkilias commented on test/integration/api_access.py
I have a little bit the feeling that should be part of the package

2024-05-07 07:19 UTC, tkilias commented on test/integration/databases_test.py
>          assert db.status == openapi.models.Status.TOCREATE and \
this would break if SaaS gets really fast in starting DBs ;-)

2024-05-07 07:42 UTC, tkilias commented on test/integration/api_access.py
> +                idle_time=int(MINIMUM_IDLE_TIME.seconds / 60),
or maybe take a look into humanfriendly

2024-05-07 07:59 UTC, ckunki commented on test/integration/databases_test.py
>          assert db.status == openapi.models.Status.TOCREATE and \
I will replace the condition by a list of accepted states.

```python 
    CREATING = "creating"
    RUNNING = "running"
    STARTING = "starting"
    TOCREATE = "tocreate"
    TOSTART = "tostart"
```

2024-05-07 07:59 UTC, ckunki commented on test/integration/api_access.py
> +        if poll_status() not in success:
The data required for actually connecting to a database (cluster) can be obtained from https://cloud.exasol.com/openapi/index.html#/Clusters/GetClusterConnection

Response contains: `dbUsername`, `dns`, `port`.

2024-05-07 08:04 UTC, ckunki commented on test/integration/api_access.py
> +        if poll_status() not in success:
First, we will add a wrapper for connecting to a database cluster (in the context for a separate ticket).

pyexasol dependency and ip whitelisting 
* will be addressed in a separate ticket
* should be clearly treated as test-only dependencies relevant only for tests inside this repo to avoid circular dependencies

2024-05-07 08:40 UTC, ckunki commented on test/integration/api_access.py
> +MINIMUM_IDLE_TIME = timedelta(minutes=15)
Will be moved to `exasol/saas/client/__init__.py` in next push.

2024-05-07 08:40 UTC, ckunki commented on test/integration/api_access.py
> +MINIMUM_IDLE_TIME = timedelta(minutes=15)
Will be moved to `exasol/saas/client/__init__.py` in next push.

2024-05-07 08:40 UTC, ckunki commented on test/integration/api_access.py
> +MINIMUM_LIFETIME = timedelta(seconds=30)
Will be moved to `exasol/saas/client/__init__.py` in next push.

2024-05-07 08:42 UTC, ckunki commented on test/integration/api_access.py
> +                response = self.delete_database(db.id, ignore_delete_failure)
As discussed: We will go with the current implementation for now.
In case we might observe problems in the future, we will improve the implementation.

2024-05-07 08:47 UTC, ckunki commented on test/integration/api_access.py
See issue #33

2024-05-07 08:51 UTC, ckunki commented on test/integration/api_access.py
> +    def wait_for_delete_clearance(self, start: datetime.time):
see next push

2024-05-07 08:59 UTC, tomuben commented on test/integration/api_access.py
> +    return f"{username}-{timestamp}"
```
    input_parameter_limits = {
        "max_database_name_length": 20,  # in characters
        "max_cluster_name_length": 40,  # in characters
        "autostop_min_idle_time": 15,  # in minutes
        "autostop_max_idle_time": 10000,  # in minutes
        "autostop_default_idle_time": 120,
    }
```

2024-05-07 09:01 UTC, tomuben commented on test/integration/api_access.py
> +                name=db_name,
`us-east-1` is not a bad decision for integration tests, as it is the largest AWS spot, and the probability that a machine is not available is less.

2024-05-07 09:01 UTC, ckunki commented on test/integration/databases_test.py
>          assert db.status == openapi.models.Status.TOCREATE and \
see next push

2024-05-07 09:05 UTC, tkilias commented on test/integration/api_access.py
> +                name=db_name,
ok, that is actually good to know, thx

2024-05-07 09:05 UTC, tkilias commented on test/integration/api_access.py
> +    return f"{username}-{timestamp}"
thx

2024-05-07 11:03 UTC, ckunki commented on test/integration/api_access.py
> +                idle_time=int(MINIMUM_IDLE_TIME.seconds / 60),
Unfortunately, `humanfriendly` only provides [coerce_seconds](https://humanfriendly.readthedocs.io/en/latest/api.html?highlight=datetime#humanfriendly.coerce_seconds) but not minutes.

2024-05-07 12:35 UTC, ckunki commented on test/integration/api_access.py
> +    return f"{username}-{timestamp}"
On the other hand, I wonder if the user name is helpful in CI builds.

2024-05-08 06:32 UTC, tkilias commented on test/integration/api_access.py
> +    return f"{username}-{timestamp}"
I think, the user name was runner, this would indicate the CI

2024-05-08 06:41 UTC, tkilias commented on test/integration/api_access.py
> +    owner = project_short_tag or getpass.getuser()
Short tag and user are not either or , we should have both

2024-05-08 08:00 UTC, tkilias approved these changes

2024-05-08 08:03 UTC, merged