Feature/#6 add nox task for generating the api
exasol/saas-api-python pull request #9
Opened 2024-04-16 14:20 UTC by ckunki

Closes #6

2024-04-17 04:43 UTC, kaklakariada requested changes

2024-04-17 04:43 UTC, kaklakariada commented on .gitattributes
> +/exasol/saas/client/openapi/**  linguist-generated
```suggestion
/exasol/saas/client/openapi/**  linguist-generated=true
```

2024-04-17 04:43 UTC, kaklakariada commented on doc/developer_guide/developer-guide.md
Rename file to developer_guide.md?

2024-04-17 04:43 UTC, kaklakariada commented on doc/developer_guide/developer-guide.md
> +[Documentation](https://docs.exasol.com/saas/administration/rest_api/rest_api.htm)
```suggestion
[API Documentation](https://docs.exasol.com/saas/administration/rest_api/rest_api.htm)
```

2024-04-17 05:55 UTC, ckunki commented on .gitattributes
> +/exasol/saas/client/openapi/**  linguist-generated
See https://github.com/github-linguist/linguist/blob/master/docs/overrides.md#generated-code
And https://github.com/AlDanial/cloc/issues/722#issuecomment-1514892486

2024-04-17 07:02 UTC, kaklakariada submitted a review, later dismissed

2024-04-17 07:49 UTC, tkilias requested changes

2024-04-17 07:49 UTC, tkilias commented on noxfile.py
>  from exasol.toolbox.nox.tasks import check # pylint: disable=unused-import
The user guide of the toolbox suggest importing with star to really get all of them
https://exasol.github.io/python-toolbox/user_guide/getting_started.html#make-the-toolbox-task-available

2024-04-17 07:49 UTC, tkilias commented on noxfile.py
> +        "update",
Does update need a generate before, or can we always use update, also if the code doesn't exist yet?

2024-04-17 07:49 UTC, tkilias commented on noxfile.py
> +        "--url", "https://cloud.exasol.com/openapi.json",
hm, now the question, should we be able to overwrite this with API of the staging or internal definiton

2024-04-17 09:47 UTC, kaklakariada approved these changes

2024-04-17 11:59 UTC, kaklakariada submitted a review, later dismissed

2024-04-17 12:01 UTC, tkilias requested changes

2024-04-17 12:01 UTC, tkilias commented on doc/developer_guide/developer_guide.md
> +* https://cloud-staging.exasol.com/internal-api.json
does not exist and should not be mentioned in a public repo

2024-04-17 12:01 UTC, tkilias commented on doc/developer_guide/developer_guide.md
> +* https://cloud-staging.exasol.com/openapi.json
should not be mentioned in a public repo

2024-04-17 12:01 UTC, tkilias commented on exasol/saas/client/__init__.py
> +SAAS_HOST = "https://cloud-staging.exasol.com"
SAAS_HOST = "https://cloud.exasol.com"

2024-04-17 12:36 UTC, kaklakariada submitted a review, later dismissed

2024-04-18 09:28 UTC, tkilias approved these changes

2024-04-18 09:52 UTC, merged